### ISSUE TITLE
We are working on similar project

### ISSUE THREAD

**Issue by darklordabc** [RobinCodeX/dota2-simple-gui#2]
https://github.com/dota2unofficial/modexplorer

Just asking if you would consider joining us, I would pay you like 24 usd an hour to help us finish it. We are progressing fast. We were going to do a vs plug in as well, there is lots of good reasons for that but ultimately we decided to focus on new modders and try to avoid text editing as much as possible, and we also wanted the tool to be usable for sublime users. 

So I'm just asking if you would consider joining us, we could really use your skill and you have the same dream of having a gui editor so it makes sense to me to work together.

**Comment by robincodex** [comment]
Thank you for your invitation, but I can't accept your invitation. I don't have much time to complete this project. As you can see, my project hasn't been updated for a long time.  
I already have my own job, I use my spare time to experience hobbies.
